version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: tactical-thieves-sqlserver
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ${SA_PASSWORD} 
      MSSQL_PID: Developer  # Utilise l'édition Express gratuite
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data: