// Angular testing tools: TestBed (test bench) and ComponentFixture (instance + DOM access).
import { ComponentFixture, TestBed } from '@angular/core/testing';
// Router: the navigation dependency. provideRouter supplies a real test router
// (required so the template's routerLinks render correctly).
import { Router, provideRouter } from '@angular/router';
// BehaviorSubject: an Observable that keeps its last value. We use it to SIMULATE
// the login state and push it (.next(...)) from the tests.
import { BehaviorSubject } from 'rxjs';
// The component under test.
import { NavbarComponent } from './navbar.component';
// The service we replace with a fake (mock).
import { AuthService } from '../../services/auth-service/auth.service';
// The app's real routes, so provideRouter knows /home, /login, etc.
import { routes } from '../app.routes';

describe('NavbarComponent', () => {
  let component: NavbarComponent;
  let fixture: ComponentFixture<NavbarComponent>;
  // Our fake AuthService: two controllable BehaviorSubjects + a spy on logout.
  let authServiceMock: {
    isLoggedIn$: BehaviorSubject<boolean>;
    username$: BehaviorSubject<string>;
    logout: jasmine.Spy;
  };
  let router: Router;

  // Small helper: returns all the <a> links currently rendered in the DOM.
  function getLinks(): HTMLAnchorElement[] {
    return Array.from(fixture.nativeElement.querySelectorAll('a'));
  }

  // Finds a specific link by its target (the href attribute generated by routerLink).
  function getLinkByHref(href: string): HTMLAnchorElement | undefined {
    return getLinks().find((a) => a.getAttribute('href') === href);
  }

  beforeEach(async () => {
    // We build the fake service. isLoggedIn$ starts at false (user logged out).
    authServiceMock = {
      isLoggedIn$: new BehaviorSubject<boolean>(false),
      username$: new BehaviorSubject<string>(''),
      logout: jasmine.createSpy('logout'),
    };

    await TestBed.configureTestingModule({
      imports: [NavbarComponent], // standalone component
      providers: [
        provideRouter(routes),                                // real router (for the routerLinks)
        { provide: AuthService, useValue: authServiceMock },  // we inject our mock
      ],
    }).compileComponents();

    fixture = TestBed.createComponent(NavbarComponent);
    component = fixture.componentInstance;
    router = TestBed.inject(Router); // we grab the router instance to spy on it
    // We spy on navigate to check the redirection WITHOUT actually changing pages.
    spyOn(router, 'navigate');
    fixture.detectChanges(); // first render
  });

  // ===================================================================
  // Group A — Routing links
  // ===================================================================

  // A1: the component instantiates without error.
  it('should create', () => {
    expect(component).toBeTruthy();
  });

  // A2: the Home and Game links are always present and point to the right routes.
  it('should always display Home and Game links with correct routes', () => {
    const links = getLinks();
    // routerLink generates an href attribute: we look up our two permanent targets.
    const hrefs = links.map((a) => a.getAttribute('href'));
    expect(hrefs).toContain('/home');
    expect(hrefs).toContain('/unity-game');
  });

  // A3: ACTION — clicking Home triggers a navigation to /home.
  it('should navigate to /home when the Home link is clicked', () => {
    // Clicking a routerLink calls navigateByUrl (NOT navigate): so that is
    // the method we spy on here. We intercept it to avoid a real navigation.
    const navigateByUrlSpy = spyOn(router, 'navigateByUrl');

    // We simulate the user clicking the Home link.
    getLinkByHref('/home')!.click();

    // A navigation was indeed triggered...
    expect(navigateByUrlSpy).toHaveBeenCalled();
    // ...and to the right URL (the received argument, converted to text, equals "/home").
    expect(navigateByUrlSpy.calls.mostRecent().args[0].toString()).toBe('/home');
  });

  // A4: ACTION — clicking Game triggers a navigation to /unity-game.
  it('should navigate to /unity-game when the Game link is clicked', () => {
    const navigateByUrlSpy = spyOn(router, 'navigateByUrl');

    getLinkByHref('/unity-game')!.click();

    expect(navigateByUrlSpy).toHaveBeenCalled();
    expect(navigateByUrlSpy.calls.mostRecent().args[0].toString()).toBe('/unity-game');
  });

  // A5: ACTION — clicking Register triggers a navigation to /register.
  // (The Register link only exists when the user is logged out, which is the
  //  initial state of our mock: nothing special to do here.)
  it('should navigate to /register when the Register link is clicked', () => {
    const navigateByUrlSpy = spyOn(router, 'navigateByUrl');

    getLinkByHref('/register')!.click();

    expect(navigateByUrlSpy).toHaveBeenCalled();
    expect(navigateByUrlSpy.calls.mostRecent().args[0].toString()).toBe('/register');
  });

  // ===================================================================
  // Group B — Logged-in vs logged-out user
  // ===================================================================

  // B1: logged out (initial state) → we see Register and Login, no Logout.
  it('should show Register and Login when logged out', () => {
    const hrefs = getLinks().map((a) => a.getAttribute('href'));
    expect(hrefs).toContain('/register');
    expect(hrefs).toContain('/login');

    // No link should contain the text "Logout".
    const hasLogout = getLinks().some((a) => a.textContent?.includes('Logout'));
    expect(hasLogout).toBeFalse();
  });

  // B2: logged in → we see "Logout <username>", and no more Register/Login links.
  it('should show Logout with username when logged in', () => {
    // We simulate logging in by pushing new values into the mock.
    authServiceMock.isLoggedIn$.next(true);
    authServiceMock.username$.next('Alice');
    fixture.detectChanges(); // re-trigger the render to reflect the new state

    // The logout link shows the username.
    const logoutLink = getLinks().find((a) => a.textContent?.includes('Logout'));
    expect(logoutLink).toBeTruthy();
    expect(logoutLink!.textContent).toContain('Alice');

    // The login/register links are gone.
    const hrefs = getLinks().map((a) => a.getAttribute('href'));
    expect(hrefs).not.toContain('/register');
    expect(hrefs).not.toContain('/login');
  });

  // ===================================================================
  // Group C — Logout functionality
  // ===================================================================

  // C1: clicking the Logout link calls the component's logout() method.
  it('should call logout() when the Logout link is clicked', () => {
    // We move to the logged-in state so the Logout link exists in the DOM.
    authServiceMock.isLoggedIn$.next(true);
    fixture.detectChanges();

    // We spy on the component's method.
    spyOn(component, 'logout');

    // We grab the Logout link and simulate the click.
    const logoutLink = getLinks().find((a) => a.textContent?.includes('Logout'));
    logoutLink!.click();

    // The (click)="logout()" binding did trigger the method.
    expect(component.logout).toHaveBeenCalled();
  });

  // C2: logout() logs out via the service THEN redirects to /home.
  it('should log out and redirect to /home', () => {
    component.logout();

    // Effect 1: the logout is requested from the service.
    expect(authServiceMock.logout).toHaveBeenCalled();
    // Effect 2: the redirection to home is triggered.
    expect(router.navigate).toHaveBeenCalledWith(['/home']);
  });
});
